export const COLORS = [
  { value: 'hot-pink', label: 'Hot pink', code: '#FA64C3' },
  { value: 'carnation', label: 'Carnation', code: '#fa4f65' },
  { value: 'coral', label: 'Coral', code: '#ff894d' },
  { value: 'koromiko', label: 'Koromiko', code: '#ffc566' },
  { value: 'turquoise', label: 'Turquoise', code: '#4cd8ba' },
  { value: 'malibu', label: 'Malibu', code: '#6be9ff' },
  { value: 'blue-ribbon', label: 'Blue ribbon', code: '#0068ff' },
  { value: 'royal-blue', label: 'Royal blue', code: '#6b49f5' },
  { value: 'white', label: 'White', code: '#ffffff' },
  { value: 'athens-gray', label: 'Athens gray', code: '#f0f0f3' },
  { value: 'iron', label: 'Iron', code: '#dedee0' },
  { value: 'french-gray', label: 'French gray', code: '#b8b9c0' },
  { value: 'mid-gray', label: 'Mid gray', code: '#606166' },
  { value: 'cape-cod', label: 'Cape cod', code: '#393d40' },
  { value: 'shark', label: 'Shark', code: '#252729' },
  { value: 'dark-gray', label: 'Dark gray', code: '#1b1c1e' },

  // Legacy
//   { value: '', label: 'None', code: '' },
//   { value: 'radical-red', label: 'Radical red', code: '#DB536A' },
//   { value: 'monza', label: 'Monza', code: '#FD3A69' },
//   { value: 'carrot-orange', label: 'Carrot orange', code: '#EC8D23' },
//   { value: 'koromiko', label: 'Koromiko', code: '#FFC566' },
//   { value: 'tradewind', label: 'Tradewind', code: '#6DBDB2' },
//   { value: 'dodger-blue', label: 'Dodger blue', code: '#4786FF' },
//   { value: 'royal-blue', label: 'Royal blue', code: '#6B48F5' },
//   { value: 'flirt', label: 'Flirt', code: '#9D0191' },
//   { value: 'black-haze', label: 'Black haze', code: '#E7EAE9' },
//   { value: 'silver', label: 'Silver', code: '#C0C0C0' },
//   { value: 'boulder', label: 'Boulder', code: '#575757' },
//   { value: 'tundora', label: 'Tundora', code: '#464646' },
//   { value: 'black', label: 'Black ', code: '#000000' },
]
